[package]
name = "verbatim-audio-wasapi"
description = "The WASAPI output device behind the audio mixer"
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true

[dependencies]
tracing.workspace = true
verbatim-audio.workspace = true
verbatim-model.workspace = true
windows.workspace = true
windows-core.workspace = true
workspace-hack = { version = "0.1", path = "../workspace-hack" }

[lints]
workspace = true
