//! Unifies the features of third-party dependencies across the workspace,
//! so every cargo command builds each dependency once, whichever packages it
//! selects. Its manifest is generated by `cargo hakari generate`; see
//! `docs/tooling.md`. It has no code.
