//! Regression test: a flight-recorder dump captured from a scripted reducer
//! session, replayed and checked against the effect counts recorded
//! alongside it (architecture section 9, milestone M2 — "reducer replay
//! tests built from live dumps"). The committed fixture pins this sequence
//! forever; [`regenerate_fixture`] below is how it was produced and how a
//! future intentional change to the scripted shapes regenerates it.

use std::fs;
use std::io::BufReader;
use std::path::PathBuf;

use verbatim_core::{RecordedInput, SrState, dump, reduce, replay};
use verbatim_model::{
    Backend, Input, NodeDetails, NodeId, NodeSnapshot, NormalizedEvent, Pid, PropertyChange, Role,
    SnapshotVersion, State, StateSet, TraceId,
};

fn fixture_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/focus_value_states.jsonl")
}

/// A focus change, a value change, and a states change on the same node —
/// a slider tabbed to at 50, dragged to 55, then disabled — reusing the
/// shapes `tests/reduce.rs` already exercises individually. This is the
/// realistic session the committed fixture pins.
fn scripted_inputs() -> Vec<Input> {
    let source = Pid(700);
    let node_id = NodeId::new(1);
    let slider = NodeSnapshot {
        id: node_id,
        backend: Backend::Uia,
        role: Role::Slider,
        name: Some("Rate".to_owned()),
        value: Some("50".to_owned()),
        states: StateSet::new(),
        details: NodeDetails::default(),
    };
    vec![
        Input::Event {
            trace_id: TraceId::mint(),
            source,
            backend: Backend::Uia,
            version: SnapshotVersion(1),
            event: NormalizedEvent::FocusChanged {
                node: slider,
                ancestors: Vec::new(),
            },
        },
        Input::Event {
            trace_id: TraceId::mint(),
            source,
            backend: Backend::Uia,
            version: SnapshotVersion(2),
            event: NormalizedEvent::ValueChanged {
                node_id,
                value: Some("55".to_owned()),
            },
        },
        Input::Event {
            trace_id: TraceId::mint(),
            source,
            backend: Backend::Uia,
            version: SnapshotVersion(3),
            event: NormalizedEvent::PropertyChanged {
                node_id,
                change: PropertyChange::States(StateSet::new().with(State::Disabled)),
            },
        },
    ]
}

#[test]
fn replays_the_committed_fixture_deterministically_and_matches_recorded_effect_counts() {
    let file = fs::File::open(fixture_path()).expect("fixture file exists");
    let mut reader = BufReader::new(file);
    let contents = dump::read_dump(&mut reader).expect("fixture parses");

    assert!(!contents.truncated, "the committed fixture is complete");
    assert!(!contents.inputs.is_empty());

    let inputs: Vec<Input> = contents.inputs.iter().map(|r| r.input.clone()).collect();

    let first = replay(&SrState::new(), &inputs);
    let second = replay(&SrState::new(), &inputs);
    assert_eq!(first, second, "replay is deterministic");

    assert_eq!(first.len(), contents.inputs.len());
    for (effects, recorded) in first.iter().zip(&contents.inputs) {
        assert_eq!(
            effects.len(),
            recorded.effect_count,
            "replayed effect count must match what the live session recorded"
        );
    }
}

/// Regenerates the committed fixture from [`scripted_inputs`] by actually
/// running each input through [`reduce`], exactly like a live reducer
/// thread would. Not part of the default test run: only an intentional
/// change to the scripted shapes above should touch the fixture, and that
/// change is reviewed as a diff to the committed file, not silently
/// regenerated by CI. Run explicitly after changing `scripted_inputs`:
/// `cargo test -p verbatim-core --test replay_fixture -- --ignored regenerate_fixture`.
#[test]
#[ignore = "regenerates the committed fixture; run explicitly, not part of the default suite"]
fn regenerate_fixture() {
    let mut state = SrState::new();
    let mut recorded = Vec::new();
    for input in scripted_inputs() {
        let (next, effects) = reduce(&state, &input);
        recorded.push(RecordedInput {
            input,
            effect_count: effects.len(),
        });
        state = next;
    }

    let mut buffer = Vec::new();
    dump::write_dump(
        &mut buffer,
        env!("CARGO_PKG_VERSION"),
        "2026-07-14T00:00:00Z",
        &recorded,
    )
    .expect("writes");

    let path = fixture_path();
    fs::create_dir_all(path.parent().expect("fixtures dir")).expect("creates fixtures dir");
    fs::write(path, buffer).expect("writes fixture");
}
